plugins {
    id "architectury-plugin" version "3.4.164"
    id "dev.architectury.loom" version "1.13.469"
    id "maven-publish"
}

architectury {
    minecraft = rootProject.minecraft_version
    platformSetupLoomIde()
    fabric()
}

version = mod_version + "+" + minecraft_version
group = maven_group

base {
    archivesName = archives_base_name
}

loom {
    silentMojangMappingsLicense()
    accessWidenerPath = file("src/main/resources/figurasvc.accesswidener")
}

repositories {
    maven { url 'https://maven.quiltmc.org/repository/release/' }
    maven { url 'https://jitpack.io' }
    maven { url = 'https://maven.maxhenkel.de/repository/public' }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        mappings("org.quiltmc:quilt-mappings:${minecraft_version}+build.${mappings}:intermediary-v2")
        officialMojangMappings()
    }

    implementation("com.github.FiguraMC.luaj:luaj-core:${project.property('luaj-figura')}")
    implementation("com.github.FiguraMC.luaj:luaj-jse:${project.property('luaj-figura')}")
    implementation("com.neovisionaries:nv-websocket-client:${websocket}")
    implementation "de.maxhenkel.voicechat:voicechat-api:2.5.0"

    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    modImplementation files("deps/figura-${figura_version}+${minecraft_version}-fabric-mc.jar")
    modRuntimeOnly "maven.modrinth:simple-voice-chat:pTfXZIdn"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = java_version.toInteger()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(java_version.toInteger())
    }
    withSourcesJar()
}

processResources {
    Map<String, Object> properties = new HashMap<>()
    properties.put("version", project.version)
    properties.put("java_version", java_version)
    properties.put("minecraft_version", minecraft_version)
    properties.put("figura_version", figura_version)
    properties.put("fabric_api_version", fabric_api_version)
    properties.put("fabric_loader_version", fabric_loader_version)
    properties.put("minecraft_dependency", minecraft_dependency)
    properties.put("mod_id", plugin_id)
    properties.put("display_name", display_name)
    properties.put("description", description)
    properties.put("authors", authors)

    properties.each { k, v -> inputs.property(k, v.toString()) }
    filesMatching("fabric.mod.json") {
        expand properties
    }
}

remapJar {
    injectAccessWidener = true
    archiveClassifier = null
}

jar {
    archiveClassifier = "dev"
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = archives_base_name
            from components.java
        }
    }

    repositories {
    }
}
